# Generated by Django 5.2.5 on 2025-11-07 00:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('imagen_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('gif_url', models.URLField(blank=True)),
                ('equipamiento', models.TextField(blank=True)),
                ('partes_cuerpo', models.TextField(blank=True)),
                ('musculos_principales', models.TextField(blank=True)),
                ('musculos_secundarios', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('consejos', models.TextField(blank=True)),
                ('variaciones', models.TextField(blank=True)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=20)),
                ('advertencias', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('usuario', 'Usuario'), ('entrenador', 'Entrenador'), ('administrador', 'Administrador')], default='usuario', max_length=20)),
                ('foto_perfil', models.URLField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('nivel_experiencia', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20)),
                ('objetivo', models.TextField(blank=True)),
                ('certificacion', models.CharField(blank=True, max_length=200)),
                ('especialidad', models.CharField(blank=True, max_length=200)),
                ('anos_experiencia', models.IntegerField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
                ('horario', models.TextField(blank=True, help_text='Horarios de atención del entrenador')),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad_clientes', models.IntegerField(default=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProgresoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pecho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brazos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('piernas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foto', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso Físico',
                'verbose_name_plural': 'Progreso Físico',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='intermedio', max_length=20)),
                ('duracion_min', models.IntegerField(default=60, help_text='Minutos')),
                ('objetivo', models.TextField(blank=True)),
                ('es_publica', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('duracion_min', models.IntegerField(blank=True, null=True)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('nivel_esfuerzo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notas', models.TextField(blank=True)),
                ('completado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.rutina')),
            ],
            options={
                'verbose_name': 'Registro de Entrenamiento',
                'verbose_name_plural': 'Registros de Entrenamientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.rutina')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('series', models.IntegerField(default=3)),
                ('repeticiones', models.IntegerField(default=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descanso_seg', models.IntegerField(default=60)),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gym.rutina')),
            ],
            options={
                'verbose_name': 'Detalle de Rutina',
                'verbose_name_plural': 'Detalles de Rutinas',
                'ordering': ['rutina', 'orden'],
            },
        ),
    ]
